config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length:{maximum: 25}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :remember_me])
        devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :email, :password, :remember_me])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :current_password])
        # devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :remember_me) }
        # devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:name, :email, :password, :remember_me) }
        # devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Edulex</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> 
  </head>

  <body>
  
    <%= render partial: "shared/header"%>
    <%= render partial: "shared/message"%>
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <%= render partial: "shared/footer"%>

  </body>

  <script>
     $('.sidenav').sidenav();
     $(".dropdown-trigger").dropdown();
  </script>
</html>

app/views/pages/about.html.erb
<h3>About Us</h3>
<div class="card z-depth-3">
    <div class="row">
        <div class="card-content white-text">
            <div class="col m6">
                <a class="twitter-timeline" href="https://twitter.com/Code4Startup" data-widget-id="584941191998877696">Tweets by @Code4Startup</a>
                
	            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
            </div>
            <div class="col m6">            
                <div class="card-panel grey lighten-5 z-depth-1">
                    <div class="row valign-wrapper">
                        <div class="col m3">
                            <%= image_tag "avatar.png", class: "circle responsive-img"%>
                        </div>
                        <div class="col m9">
                            <span class="black-text">                      
                                I don't know what to tell, so you tell me about world. I wanna be everything at once.Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium natus maiores deserunt aspernatur nulla excepturi facilis consequatur quae optio recusandae quia vero, non cum qui deleniti odio, ut facere? Sunt!Ab quibusdam, repudiandae eligendi provident.
                            </span>
                        </div>
                    </div>
                </div>                
                
            </div>
        </div>
    </div>
</div>

app/views/shared/_footer.html.erb
<footer class="page-footer  indigo darken-3">
    <div class="container">
    <div class="row">
        <div class="col l6 s12">
        <h5 class="white-text">edulex</h5>
        <p class="grey-text text-lighten-4">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.
        </p>
        </div>
        <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Social</h5>
        <ul>
            <li><a class="grey-text text-lighten-3" href="#!">Twitter</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Facebook</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Google Plus</a></li>
        </ul>
        </div>
    </div>
    </div>
    <div class="footer-copyright">
    <div class="container">
    © 2020 Copyright edulex
    <%= link_to "About Us", pages_about_path, :class => "grey-text text-lighten-4 right" %>
    </div>
    </div>
</footer>

app/views/shared/_header.html.erb
<header>
    <ul id="dropdown1" class="dropdown-content">
        <li><%= link_to "My Profile", edit_user_registration_path %></li>
        <li><a href="#!">My Courses</a></li>
        <li class="divider"></li>
        <li> <%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
    </ul>

    <ul id="dropdown2" class="dropdown-content">
        <li><%= link_to "My Profile", edit_user_registration_path %></li>
        <li><a href="#!">My Courses</a></li>
        <li class="divider"></li>
        <li> <%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
    </ul>

    <nav class=" indigo darken-2 z-depth-1">
        <div class="container">
        <div class="nav-wrapper">
            <a href="#!" class="brand-logo">edulex.live</a>
            <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">
            <li><a href="#">Courses</a></li>
            <% if (!user_signed_in?) %>
                <li><%= link_to "Log in", new_user_session_path %> </li>
                <li><%= link_to "Join for free", new_user_registration_path %></li>
            <% else %>
                <li><a class="dropdown-trigger" href="#!" data-target="dropdown1"><%= current_user.name%><i class="material-icons right">arrow_drop_down</i></a></li>
            <% end %>
            </ul>
        </div>
        </div>
    </nav>

    <ul class="sidenav" id="mobile-demo">
        <li><a href="#">Courses</a></li>
        <% if (!user_signed_in?) %>
            <li><%= link_to "Log in", new_user_session_path %> </li>
            <li><%= link_to "Join for free", new_user_registration_path %></li>
        <% else %>
            <li><a class="dropdown-trigger" href="#!" data-target="dropdown2"><%= current_user.name%><i class="material-icons right">arrow_drop_down</i></a></li>
        <% end %>
    </ul>
</header>

app/views/shared/_message.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>